name: libgit2_ffigen

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  ffigen:

ffigen:
  name: NativeLibrary
  description: 'Bindings for libgit2'
  output: '../lib/src/generated_bindings.dart'
  llvm-path:
   - '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr'
  compiler-opts:
   - '-I../ios/libgit2-1.1.0/include'
   - '-Wno-nullability-completeness'
  headers:
    entry-points:
      - '../ios/libgit2-1.1.0/include/git2.h'
  functions:
    include:
     - git_libgit2_features
     - git_libgit2_init
     - git_libgit2_shutdown
     - git_error_last
     - git_error_set_str
     - git_repository_init
     - git_repository_init_ext
     - git_repository_open
     - git_repository_state
     - git_repository_state_cleanup
     - git_repository_free
     - git_repository_head_unborn
     - git_reference_name
  structs:
    dependency-only: opaque
    include:
     - git_error
     - git_strarray
     - git_buf
  enums:
    exclude:
     - .*
  macros:
    include:
     - GIT_FETCH_OPTIONS_VERSION
     - GIT_PUSH_OPTIONS_VERSION
     - GIT_STATUS_OPTIONS_VERSION
     - GIT_CLONE_OPTIONS_VERSION
     - GIT_CHECKOUT_OPTIONS_VERSION
     - GIT_MERGE_OPTIONS_VERSION
  globals:
    exclude:
    - .*
  typedef-map:
    'size_t': 'IntPtr'
