name: libgit2_ffigen

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  ffigen:

ffigen:
  name: NativeLibrary
  description: 'Bindings for libgit2'
  output: '../lib/src/generated_bindings.dart'
  llvm-path:
   - '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr'
  compiler-opts:
   - '-I../ios/libgit2-1.1.0/include'
   - '-Wno-nullability-completeness'
  headers:
    entry-points:
      - '../ios/libgit2-1.1.0/include/git2.h'
  functions:
    include:
     - git_libgit2_features
     - git_libgit2_init
     - git_libgit2_shutdown
     - git_error_last
     - git_error_set_str
     - git_repository_init
     - git_repository_init_ext
     - git_repository_open
     - git_repository_state
     - git_repository_state_cleanup
     - git_repository_free
     - git_repository_head_unborn
     - git_reference_name
     - git_repository_head
     - git_repository_set_head
     - git_graph_ahead_behind
     - git_strarray_dispose
     - git_remote_free
     - git_remote_fetch
     - git_remote_push
     - git_remote_list
     - git_remote_create
     - git_remote_delete
     - git_remote_lookup
     - git_status_list_new
     - git_status_list_free
     - git_status_list_entrycount
     - git_status_byindex
     - git_repository_index
     - git_index_free
     - git_index_write_tree
     - git_tree_lookup
     - git_commit_lookup
     - git_commit_free
     - git_annotated_commit_from_ref
     - git_annotated_commit_id
     - git_annotated_commit_free
     - git_reference_dwim
     - git_branch_upstream
     - git_branch_name
     - git_reference_free
     - git_buf_dispose
     - git_index_add_bypath
     - git_index_remove_bypath
     - git_index_write
     - git_tree_free
     - git_signature_now
     - git_signature_free
     - git_oid_cpy
     - git_reference_name_to_id
     - git_reference_set_target
     - git_reference_resolve
     - git_reference_target
     - git_commit_create
     - git_merge_analysis
     - git_merge
     - git_checkout_tree
     - git_checkout_head
     - git_credential_userpass_plaintext_new
     - git_clone
     - git_repository_mergehead_foreach
  structs:
    dependency-only: opaque
    include:
     - git_error
     - git_strarray
     - git_buf
     - git_signature
     - git_oid
     - git_status_entry
     - git_diff_delta
     - git_remote_callbacks
  enums:
    exclude:
     - .*
  macros:
    include:
     - GIT_FETCH_OPTIONS_VERSION
     - GIT_PUSH_OPTIONS_VERSION
     - GIT_STATUS_OPTIONS_VERSION
     - GIT_CLONE_OPTIONS_VERSION
     - GIT_CHECKOUT_OPTIONS_VERSION
     - GIT_MERGE_OPTIONS_VERSION
     - GIT_REPOSITORY_INIT_OPTIONS_VERSION
  globals:
    exclude:
    - .*
  typedef-map:
    'size_t': 'IntPtr'
